package edu.fudn.entities;
// Generated Jan 2, 2021 10:52:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="Categories"
    ,schema="dbo"
    ,catalog="FUD"
)
public class Category  implements java.io.Serializable {


     private int categoryId;
     private String name;
     private Set<Product> productses = new HashSet<Product>(0);

    public Category() {
    }

    public Category(String name, Set<Product> productses) {
       this.name = name;
       this.productses = productses;
    }
   
     @Id 
     //id là trường tự tăng nên có thêm dòng @GeneratedValue(strategy = GenerationType.IDENTITY)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="CategoryId", unique=true, nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Product> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Product> productses) {
        this.productses = productses;
    }




}


