package edu.fudn.entities;
// Generated Jan 2, 2021 10:52:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="Products"
    ,schema="dbo"
    ,catalog="FUD"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private Category categories;
     private String description;
     private String image;
     private Date manufacturedDate;
     private String name;
     private double price;
     private int quantity;
     private String status;

    public Product() {
    }

	
    public Product(Category categories, String name, double price, int quantity) {
        this.categories = categories;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }
    public Product(Category categories, String description, String image, Date manufacturedDate, String name, double price, int quantity, String status) {
       this.categories = categories;
       this.description = description;
       this.image = image;
       this.manufacturedDate = manufacturedDate;
       this.name = name;
       this.price = price;
       this.quantity = quantity;
       this.status = status;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="ProductId", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoryId", nullable=false)
    public Category getCategories() {
        return this.categories;
    }
    
    public void setCategories(Category categories) {
        this.categories = categories;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ManufacturedDate", length=10)
    public Date getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(Date manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Price", nullable=false, precision=53, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


